### ISSUE TITLE
Foundry randomly corrupts the world on a blocktick

### ISSUE THREAD

**Issue by DaeTheDerg** [Lucreeper74/Create-Metallurgy#7] opened 2024-06-14 21:14 UTC
**Describe the bug**
createmetallurgy:foundry_top causes a 'block entity being ticked' error that makes the world unplayable

**To Reproduce**
1.  Build a foundry
2.  Wait for crash

**Screenshot**
![2024-06-14_21 23 07](https://github.com/Lucreeper74/Create-Metallurgy/assets/80906771/375a931e-a722-45d2-9f21-572d48b387af)

**Environment:**
 - Minecraft 1.20.1
 - Neoforge 47.1.106
 - Create 0.5.1.f
 - Create Metallurgy 0.0.2-1.20.1

below is a crash report recorded, in which I create a superflat world, then built a foundry as shown in the image above, and after just a few minuites, the game crashes ( at 21:42:21 ) and the world is no longer acessable as the game crashes instantly upon loading it again.

**[Crash Report](https://gist.github.com/DaeTheDragon/94c7e98245896f9eba18b544e726ccf6)**

**Comment by Lucreeper74** [comment] 2024-06-14 22:19
Hey @DaeTheDragon !
Sorry for your disappointing, this is a know issue, it will be fixed and push tomorrow i think. In the next update, all world with this error when join world will disapear and normally, you will be able to get back your world.

Thanks to improve Create Metallurgy by taking the time to report issues!

**Comment by Lucreeper74** [comment] 2024-06-14 22:21
Just a comment on your foundry build: 
There is two build to use Create Metallurgy for now.
First, you will need a Foundry with only Blaze burner on top a Foundry Basin and on top again a Foundry Lid
The second is the same setup and replace the foundry lid by a Glassed Foundry Lid and a Foundry Mixer on top.

It will not work with you use a Foundry Lid with a Foundry Mixer that two setup independently.

**Comment by DaeTheDerg** [comment] 2024-06-14 22:23
> Hey @DaeTheDragon ! This is a know issue, it will be fixed and push tomorrow i think. In the next update, all world with this error when join world will disapear and normally, you will be able to get back your world.

great! glad to hear it, thanks


> Just a comment on your foundry build: There is two build to use Create Metallurgy for now. First, you will need a Foundry with only Blaze burner on top a Foundry Basin and on top again a Foundry Lid The second is the same setup and replace the foundry lid by a Glassed Foundry Lid and a Foundry Mixer on top.
> 
> It will not work with you use a Foundry Lid with a Foundry Mixer that two setup independently.

ah okay, thanks for the info there <3

**Comment by Lucreeper74** [comment] 2024-06-14 22:26
Alright, if you have any others questions, you can join Create Metallurgy Discord [here](https://discord.gg/KGQr5a2qc9)

This issue will be close once the commit that fix it be pushed to warn others peoples.

**Comment by Lucreeper74** [comment] 2024-06-15 15:08
Hi again @DaeTheDragon!
The bug was found, a simple error on my part. However, I would like to optimize the part of the code that manages this and I tried to reproduce the bug to evaluate the performance used by this part but without success.
Could you give me the save of the world please?

**Comment by DaeTheDerg** [comment] 2024-06-15 22:26
Sure! I used the same world to test the 1.19.2 version to confirm the bug was present there too before making the report, hopefully, that's okay!
if not it only ever seems to take between two and ten minutes before the world corrupts in either version after building the foundry so I can make another easily

[Here's the world in an archive](https://github.com/user-attachments/files/15855510/testing.tar.gz)!

**Comment by Lucreeper74** [comment] 2024-06-15 23:18
Thanks to you, now I understood how stupid I was LMAO.
To put it simply, I thought the error was quite deep in the way Minecraft worked and so I needed to think more about it to avoid performance issues if I did it wrong. In fact, thanks to your backup I was able to reproduce the crash in my debugger which allows me to check the exact behavior of my code in real time. All this to realize that I had forgotten when displaying the temperature on the gauge, a rarely used intermediate state of the Blaze Burner and which therefore only occurred in a very specific situation.

This as been fixed due to a single line in this [commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/4f235c277f4e86b4d9e8c80a8c2003b5b6b7a931)

Your world will be accessible after updating Create Metallurgy

**Closed as completed by Lucreeper74** 2024-06-15 23:18 UTC
Labels: Bug 🐜

**Comment by Lucreeper74** [comment] 2024-06-15 23:31
> Sure! I used the same world to test the 1.19.2 version to confirm the bug was present there too before making the report, hopefully, that's okay! if not it only ever seems to take between two and ten minutes before the world corrupts in either version after building the foundry so I can make another easily
> 
> [Here's the world in an archive](https://github.com/user-attachments/files/15855510/testing.tar.gz)!

However, funny worldsave preview image ^^

**Comment by DaeTheDerg** [comment] 2024-06-16 00:16
Thanks so much, I'm glad it was an easy fix ^.=.^
