### ISSUE TITLE
[BUG 🐜] Basin & table filling in before removing item.

### ISSUE THREAD

**Issue by CravenCraft** [Lucreeper74/Create-Metallurgy#24] opened 2024-08-14 20:49 UTC
**Describe the bug**
Don't know if this is intended behavior or not (if so, then feel free to just close this issue), but when either the **Casting Basin** or **Casting Table** has a created item in it from a being previously filled, it will immediately start filling the basin/table again before removing the item. Just feels odd behavior especially when casting something like an **iron block**. When the created iron block is removed, the basin/table is already filled with molten metal and immediately creates another iron block. 

**To Reproduce**
1. Create a fluid piping system that feeds into either a **Casting Basin** or a **Casting Table**
2. Fill the system with any molten metal.
3. The basin/table will be filled with the molten metal.
4. The first recipe (in this case an **iron block**) will begin to be crafted.
5. Once the recipe is finished, **but not before the crafted item is removed**, the basin/table will be filled with molten metal again.

**Expected behavior**
5. Once the recipe is finished, **but not before the crafted item is removed**, the basin/table will be **NOT** filled with molten metal again until the crafted item is removed.

**Screenshots**
**Jade** showing that the basin is filled with molten metal again even though the created iron block has not been removed yet.
![image](https://github.com/user-attachments/assets/924d1bbd-f4a0-4a37-8a1b-a3328b514c68)

**Environment:**
 - MC/Forge version - 1.20.1
 - Create version - 0.5.1.f
 - Create Metallurgy version - 0.0.5

**Comment by Lucreeper74** [comment] 2024-08-24 20:24
Hey @CravenCraft 👋
Sorry for being late. I announced a week ago that I was going on vacation and so on completely stopping development and therefore ticket issues etc.

For your problem, don't worry, this is not a bug. Just an oversight on my part. But rest assured, I have completely reworked the code for the Casting Basin/Table and will work similarly to TiC. Which means that this will no longer happen.

However thanks to take the time to write that detailed issue! That really help me to find a bug.
If you have any other questions, don't hesitate. I will close this post if I don't get answers in the next few days!

**Comment by CravenCraft** [comment] 2024-08-24 23:06
No worries. I have a handful of bugs for my own mods that I need to look into. Finding time to fix them all is tough haha. 

But nice! This mod scratches the itch that other forging mods don't really hit. Can't wait to see how it evolves in the future!

**Comment by Lucreeper74** [comment] 2024-08-26 22:40
Thanks a lot! That give me a lot of motivation! ❤️ 
I'm bit curious, i will check your mods in ur Github repos.

**Comment by Lucreeper74** [comment] 2024-09-10 13:12
Hey @CravenCraft 👋 
Sorry for being late, see on Create Metallurgy Discord why the development is so slow. But I have finally push the code for the rework of Casting Basin/Table with the dynamic fluid capacity depending on the recipe requierement. You can found the main commit here that adding the feature -> [Github Commit](https://github.com/Lucreeper74/Create-Metallurgy/commit/3a674ff32bc3435c76b8fd98884cb8174546fa91)

**Closed as completed by Lucreeper74** 2024-09-10 13:12 UTC
Labels: Bug 🐜
