### ISSUE TITLE
Textures Display Exception

### ISSUE THREAD

**Issue by Qi-Month** [Lucreeper74/Create-Metallurgy#8] opened 2024-06-16 10:30 UTC
When Molten Iron exists in the Basin, placing the Casting Basin or Casting Table will cause the texture of Molten Iron to disappear, but the use is normal.
![image](https://github.com/Lucreeper74/Create-Metallurgy/assets/115912382/d383f44e-03c7-4f0f-b7d0-452b8df95e06)

Environment
1.20.1-Forge-47.2.30

**Comment by Lucreeper74** [comment] 2024-06-16 12:14
Hello again @Qi-Month!

I can't be able to reproduce the bug, I'm not sure I understand your explanation.
However, visuals bugs can be occured from others mods you are using maybe. It look like you are using a modpack. Especially Rubidium or Embbedium ?

_Thank you for being very active in the bug report, it helps me improve Create Metallurgy._

**Comment by Lucreeper74** [comment] 2024-06-17 18:07
If i don't have any news of this issues within few days, I will close it because no one else has reported this problem and I am not able to fix it.

**Closed as completed** 2024-06-23 15:08 UTC
Labels: Bug 🐜
